// No custom map loaded. Replace this file with one generated by the Map Editor.
// Use the "Download Map File" button in editor.html, then place the downloaded
// file here at js/saved_map.js to load your custom map in-game.
